#!/bin/sh
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
echo "========================================="
echo " Welcome to my custom Linux Kernel!      "
echo "========================================="
exec /bin/sh
